import { IconBrandCodesandbox } from '@tabler/icons-react'

export const tasks = [
  {
    logo: <IconBrandCodesandbox />,
    task: 'Legacy System Migration',
    postedBy: 'TechCorp Inc.',
    posted: '2024-06-03T09:30:00',
    expires: '2024-07-03T17:00:00',
    price: 1500,
    connected: false,
    desc: 'Migrate legacy systems from COBOL to a modern programming language while ensuring zero downtime and data integrity.',
  },
  {
    logo: <IconBrandCodesandbox />,
    task: 'Real-time Data Visualization',
    postedBy: 'DataViz Co.',
    posted: '2024-06-03T10:15:00',
    expires: '2024-06-30T15:45:00',
    price: 1200,
    connected: false,
    desc: 'Develop a real-time data visualization tool that can handle high-frequency trading data and display it in an interactive dashboard.',
  },
  {
    logo: <IconBrandCodesandbox />,
    task: 'Quantum Computing Algorithm Development',
    postedBy: 'Quantum Leap',
    posted: '2024-06-03T11:00:00',
    expires: '2024-08-01T14:30:00',
    price: 3000,
    connected: true,
    desc: 'Design and implement quantum algorithms to solve complex optimization problems more efficiently than classical algorithms.',
  },
  {
    logo: <IconBrandCodesandbox />,
    task: 'AI Ethics Framework',
    postedBy: 'EthicsFirst',
    posted: '2024-06-03T12:45:00',
    expires: '2024-07-15T13:00:00',
    price: 1800,
    connected: false,
    desc: 'Create a comprehensive AI ethics framework that addresses biases, transparency, and accountability in AI systems.',
  },
  {
    logo: <IconBrandCodesandbox />,
    task: 'Secure Multi-Party Computation',
    postedBy: 'SecureTech',
    posted: '2024-06-03T08:30:00',
    expires: '2024-07-20T16:00:00',
    price: 2000,
    connected: true,
    desc: 'Implement a secure multi-party computation protocol to enable collaborative data analysis without revealing sensitive information.',
  },
  {
    logo: <IconBrandCodesandbox />,
    task: 'Autonomous Drone Navigation',
    postedBy: 'DroneMaster',
    posted: '2024-06-03T14:15:00',
    expires: '2024-07-10T18:30:00',
    price: 2500,
    connected: false,
    desc: 'Develop an autonomous navigation system for drones that can operate in complex environments without human intervention.',
  },
  {
    logo: <IconBrandCodesandbox />,
    task: 'Blockchain-based Voting System',
    postedBy: 'VoteSecure',
    posted: '2024-06-03T09:00:00',
    expires: '2024-07-31T11:30:00',
    price: 2200,
    connected: false,
    desc: 'Design a blockchain-based voting system that ensures security, transparency, and tamper-proof election results.',
  },
  {
    logo: <IconBrandCodesandbox />,
    task: 'Natural Language Processing for Legal Documents',
    postedBy: 'LegalTech',
    posted: '2024-06-03T10:45:00',
    expires: '2024-07-25T13:15:00',
    price: 1700,
    connected: false,
    desc: 'Develop an NLP tool to automatically analyze and summarize legal documents, highlighting key information and potential risks.',
  },
  {
    logo: <IconBrandCodesandbox />,
    task: 'High-Frequency Trading Bot',
    postedBy: 'FinTech Innovations',
    posted: '2024-06-03T13:30:00',
    expires: '2024-07-05T14:45:00',
    price: 2800,
    connected: false,
    desc: 'Create a high-frequency trading bot that can execute trades within microseconds based on real-time market data analysis.',
  },
  {
    logo: <IconBrandCodesandbox />,
    task: 'Smart Contract Development',
    postedBy: 'CryptoDev',
    posted: '2024-06-03T15:00:00',
    expires: '2024-06-29T12:30:00',
    price: 1400,
    connected: true,
    desc: 'Develop secure and efficient smart contracts for a decentralized finance (DeFi) platform, ensuring compliance with industry standards.',
  },
]
